s="Tops Technologies"

print(len(s))
print(s)
print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.swapcase())
print(s.center(40,"*"))
print(s.count("o"))
print(s.endswith("ese"))
print(s.startswith("To"))
print(s.find("log"))
print(s.index("T"))
print("tops123".isalnum())
print("tops".isalnum())
print("123".isalnum())
print("tops 123".isalnum())
print("tops".isalpha())
print("123.10".isnumeric())
print("123.10".isdigit())
print("tops tech".istitle())
print("TOPS".isupper())
print("tops".islower())
print("".isspace())
